version: "2"

run:
  timeout: 5m
  go: '1.21'
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - goheader
    - gomodguard
    - makezero
    - prealloc
    - predeclared
    - thelper
    - tparallel
    - wastedassign

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  revive:
    confidence: 0
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN
  goimports:
    local-prefixes: github.com/autotime/autotime

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - lll
        - goconst
        - gosec
        - dupl
    - linters:
        - lll
      source: "^//go:generate "
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "Use of builtin 'new' not recommended"
      linters:
        - gocritic

severity:
  default-severity: error